### ISSUE TITLE
checksum mismatch cant download and install

### ISSUE THREAD

**Issue by oxgreyhound** [Brum3ns/firefly#10]
go: downloading github.com/Brum3ns/firefly v1.3.1
go: github.com/Brum3ns/firefly/cmd/firefly@latest: github.com/Brum3ns/firefly@v1.3.1: verifying module: checksum mismatch
        downloaded: h1:mfhkRhNJxukwzc8pOw+x1SBpcuC6eev37gJAl8Wv9v0=
        sum.golang.org: h1:uY5MrbiK1pJvYWb1qQg/GRo1kDVOgYeBnWNMgVvYml4=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

**Comment by Brum3ns** [comment]
This should now be fixed in version >= 1.4.X
