### ISSUE TITLE
Error on first usage

### ISSUE THREAD

**Issue by edoardottt** [Brum3ns/firefly#2]
I've just installed firefly using
```console
go install -v github.com/Brum3ns/firefly/cmd/firefly@latest
```

Then I tried the tool with
```
firefly -u 'http://example.com/?query=FUZZ'
```

and I got:
```
...
________________________________________________________________ 

[INF] Grep Wordlist[s] setup in process
2023/02/11 11:41:06 [FAI] open db/yml/transformation.yml: no such file or directory
```

A fix could be install the database in the `.config` directory (only on Linux) if it's the first time running the tool or the db is missing.  
Or if the database is not too big it could be possible to transform txt and yaml files to go files exporting global variables (a map or a list for example), this completely avoids the "installation" part told before that will be different for each OS.

**Comment by Brum3ns** [comment]
Hey,

Thanks for mentioning I will add a `precheck.go` file that automate this process very soon!

Regards
