### ISSUE TITLE
9

### ISSUE THREAD

**Issue by sasholy** [Brum3ns/firefly#3]

**Comment by Brum3ns** [comment]
Hey!

Error fixed!
Run: `cmd/firefly/firefly.go` there was a typo in the installation command.

Thank you!

Regards

**Comment by Brum3ns** [comment]
Let me know if it works now!

**Comment by sasholy** [comment]
> cmd/firefly/firefly.go

```
┌──(kali㉿kali)-[~/firefly]
└─$ cmd/firefly/firefly.go
cmd/firefly/firefly.go: 1: package: not found
cmd/firefly/firefly.go: 4: Syntax error: newline unexpected (expecting ")")
```

**Comment by Brum3ns** [comment]
You need to run `go run cmd/firefly/firefly.go` (if installed with **git clone**) 
v1.1 will soon be launched
