### ISSUE TITLE
Add support for filter by number of milliseconds to the first response byte

### ISSUE THREAD

**Issue by reewardius** [Brum3ns/firefly#6]
Hi, great utility, better than ffuf in some points, but definitely lacking a flag that would allow you to search for attacks based on time.

-mt Filter by the number of milliseconds to the first response byte, either more or less. EXAMPLE: >100 or <100

I would like to see this filter in firefly!

**Comment by Brum3ns** [comment]
Hey reewardius!

I have done a ton of new things for Firefly and cleaned a lot of junk code (inc bugs). This was one of the first things I added! ;)

The filter in v1.1 that I hope to soon release will offer great filtering and a lot more!

Stay tuned! :)
